<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <EnableSdkContainerSupport>true</EnableSdkContainerSupport>
    <ContainerFamily>alpine</ContainerFamily>
    <ContainerRepository>chronos-api</ContainerRepository>
    <ContainerImageTags>latest;10.0-alpine</ContainerImageTags>
    <ContainerRuntimeIdentifier>linux-musl-x64</ContainerRuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <ContainerEnvironmentVariable Include="DOTNET_EnableDiagnostics" Value="0" />
    <ContainerEnvironmentVariable Include="ASPNETCORE_HTTP_PORTS" Value="8080" />
    <ContainerLabel Include="org.opencontainers.image.authors" Value="Victor Lima Costa" />
    <ContainerLabel Include="org.opencontainers.image.vendor" Value="VictorLCosta" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\Application.csproj" />
    <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
  </ItemGroup>

</Project>
